In [3]:
import numpy as np 
a=np.array([[20,50],[40,20]])
print(np.append(a,[20,100]))

[ 20  50  40  20  20 100]


In [9]:
print(np.insert(a,[1,2],[24],axis=0)) # array,index,value

[[20 50]
 [24 24]
 [40 20]
 [24 24]]


In [18]:
print(a)
print()
print(np.delete(a,1, axis = 1))

[[20 50]
 [40 20]]

[[20]
 [40]]
