In [9]:
import numpy as np
arr=np.array([12,14,16,18])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.mean(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

60
12
18
4
15.0
[12 26 42 60]
[   12   168  2688 48384]


In [21]:
a=[100,300,400,105,30]
b=[3,5,6,2,9]
price=np.array(a)
quantity=np.array(b)
print(price)
print(quantity)
print()
c=np.cumprod([price,quantity],axis=0)
print(c)
print()
print(c[1].sum())


[100 300 400 105  30]
[3 5 6 2 9]

[[ 100  300  400  105   30]
 [ 300 1500 2400  210  270]]

4680
