In [1]:

a=[20,10,40]
b=[23,45,67]
print(a+b)

[20, 10, 40, 23, 45, 67]


In [7]:
# Concatenate   
import numpy as np
arr1=np.array(a)
arr2=np.array(b)
print(np.concatenate([arr1,arr2]))

[20 10 40 23 45 67]


In [11]:
arr3=np.array([[10,20],[15,25]])
arr4=np.array([[12,14],[15,17]])
print(np.concatenate([arr3,arr4]))  

[[10 20]
 [15 25]
 [12 14]
 [15 17]]


In [12]:
# concatenate horizontal
print(np.concatenate([arr3,arr4],axis=1))

[[10 20 12 14]
 [15 25 15 17]]


In [13]:
# concatenate horizontal
print(np.hstack([arr3,arr4]))

[[10 20 12 14]
 [15 25 15 17]]


In [14]:
# concatenate vertical 
print(np.vstack([arr3,arr4]))

[[10 20]
 [15 25]
 [12 14]
 [15 17]]


In [19]:
# split array 
a=np.array([[10,20],[30,40]])
print(np.array_split(a,3))
print(a[0])
           

[array([[10, 20]]), array([[30, 40]]), array([], shape=(0, 2), dtype=int32)]
[10 20]
