In [6]:
import numpy as np
arr1=np.array([[20,10],[15,25]])
arr2=np.array([[10,20],[15,5]])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.subtract(arr1,arr2))


[[30 30]
 [30 30]]
[[30 30]
 [30 30]]
[[ 10 -10]
 [  0  20]]
[[ 10 -10]
 [  0  20]]


In [10]:
import numpy as np
arr1=np.array([[20,10],[15,25]])
arr2=np.array([[10,20],[15,5]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[200 200]
 [225 125]]
[[200 200]
 [225 125]]
[[2.  0.5]
 [1.  5. ]]
[[2.  0.5]
 [1.  5. ]]
